// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCr5R29u71rxAFWPkj60-gJZ4KYa-Hbr9E',
    appId: '1:97344155368:web:5281276a7858c74e48e35d',
    messagingSenderId: '97344155368',
    projectId: 'chat-app-a4b6a',
    authDomain: 'chat-app-a4b6a.firebaseapp.com',
    storageBucket: 'chat-app-a4b6a.appspot.com',
    measurementId: 'G-0HHQWQ93P7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmwgS917gmaUol3fG-14pGqLnFhWuuquw',
    appId: '1:97344155368:android:f7912430b0127bbb48e35d',
    messagingSenderId: '97344155368',
    projectId: 'chat-app-a4b6a',
    storageBucket: 'chat-app-a4b6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXepzatA7n3gPyHnVH8DISq7VtknzjyA4',
    appId: '1:97344155368:ios:292dbaa8af8316d548e35d',
    messagingSenderId: '97344155368',
    projectId: 'chat-app-a4b6a',
    storageBucket: 'chat-app-a4b6a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXepzatA7n3gPyHnVH8DISq7VtknzjyA4',
    appId: '1:97344155368:ios:292dbaa8af8316d548e35d',
    messagingSenderId: '97344155368',
    projectId: 'chat-app-a4b6a',
    storageBucket: 'chat-app-a4b6a.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCr5R29u71rxAFWPkj60-gJZ4KYa-Hbr9E',
    appId: '1:97344155368:web:c60d04265abf5a9a48e35d',
    messagingSenderId: '97344155368',
    projectId: 'chat-app-a4b6a',
    authDomain: 'chat-app-a4b6a.firebaseapp.com',
    storageBucket: 'chat-app-a4b6a.appspot.com',
    measurementId: 'G-SMT5YYHP46',
  );

}